### ISSUE TITLE
Keep order of selected fields

### ISSUE THREAD

**Issue by matthenning** [Icinga/icingaweb2-module-elasticsearch#28]
Currently the order in which you define fields in the event type menu is not reflected when viewing the events table.
It would be great if the field order would be kept and the events table's columns are ordered accordingly.

For example my event type configuration looks like this:
![grafik](https://user-images.githubusercontent.com/5699183/38622546-b28ecbd2-3da3-11e8-8986-3e22c60a732c.png)

But the resulting events table looks like this:
![grafik](https://user-images.githubusercontent.com/5699183/38622606-d2efa04a-3da3-11e8-83f5-addd38091707.png)

I would have expected the columns to be in this order:
@timestamp | host | service | state | check_result.output

**Comment by jediblair** [comment]
+1 on this. I wouldn't mind so much just if the @timestamp field was displayed first (it always seems to be second for me, which is just weird).

**Comment by GalipoliX** [comment]
Definitely +1 on this! I try to show Firewall Logs of specific systems and this is really annoying to read if the fields are scrambled around.

**Comment by GalipoliX** [comment]
See #45
