### ISSUE TITLE
Timestamps display in UTC

### ISSUE THREAD

**Issue by matthenning** [Icinga/icingaweb2-module-elasticsearch#29]
## Expected Behavior

@timestamp is translated to browser/server timezone when viewing the events table

## Current Behavior

The time is displayed in UTC

## Steps to Reproduce (for bugs)

- Set the timezone of an Icinga host to Europe/Berlin (UTC+2)
- Collect logs with filebeat (in my case the icinga2.log) on this host and send them to elasticsearch
- View collected events in Kibana and verify that the event has the correct time (you should see the timestamp in UTC when viewing the raw JSON, and converted to UTC+2 otherwise)
- Now view the same event using the icingaweb2 module
- You should see, that the icingaweb2 module doesn't convert the time to UTC+2

## Your Environment
* Module version (System - About): 1.0.0
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): 2.8.2
* Elasticsearch version (`curl http://localhost:9200`): 5.6.8
* Operating System and version: Debian Stretch
* Webserver, PHP versions: nginx/1.10.3, PHP 7.0.27-0+deb9u1

**Comment by MarcusCaepio** [comment]
Confirming!

**Comment by GalipoliX** [comment]
See #44

**Comment by piotr3439** [comment]
> See #44

For me, this solution does not work

Parse error: syntax error, unexpected '$value' (T_VARIABLE) in /usr/share/icingaweb2/modules/elasticsearch/library/Elasticsearch/Elastic.php on line 43

**Comment by dnsmichi** [comment]
The patch misses a semi-colon at the end of line 42.

**Comment by lippserd** [comment]
Fixed w/ #44
