### ISSUE TITLE
[dev.icinga.com #11376] Timeperiod selector/filter

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-elasticsearch#3]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11376

**Created by mfrosch on 2016-03-14 13:51:56 +00:00**

Assignee: _mfrosch_
Status: _Assigned_ 
Target Version: _1.0.0_
Last Update: _2016-04-05 15:32:49 +00:00 (in Redmine)_

---

Allow proper filtering by time, for check and gui.

This value should be adjustable by the user via a simple widget.

**Comment by lazyfrosch** [comment]
With the normal filter widget `@timestamp` is available, but it's not easily usable.

Bringing up errors like this:

```
Elasticsearch json error 400: {"root_cause":[{"type":"parse_exception","reason":"failed to parse date field [2017-06-14 10:45:00] with format [strict_date_optional_time||epoch_millis]"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"logstash-2017.06.13","node":"BBj1Z5zESquKneMIBAZ6Ow","reason":{"type":"parse_exception","reason":"failed to parse date field [2017-06-14 10:45:00] with format [strict_date_optional_time||epoch_millis]","caused_by":{"type":"illegal_argument_exception","reason":"Unrecognized chars at the end of [2017-06-14 10:45:00]: [ 10:45:00]"}}}]}
```
