### ISSUE TITLE
How to access Elasticsearch configured Data

### ISSUE THREAD

**Issue by abunet** [Icinga/icingaweb2-module-elasticsearch#32]
Hi,

I've installed, enable and configure the elasticsearch module.
from the command line if I write:
`icingacli elasticsearch check --instance probook4730s --crit 3 --warn 3 --index logstash-* --filter=host=motion-* --from=-1d
`
i get the following output:
`CRITICAL - 7 hits`

However, if I access the Icingaweb2 interface I can't see any data relative to the elastic index.

In the documentation of the module, it isn't very clear where the elastic data table is available.
I've read the about section https://github.com/Icinga/icingaweb2-module-elasticsearch#about
it says that _you can browse events via the host action Elasticsearch Events_
can you explain how achieve this?

icinga2 version: r2.8.2-1

Thanks

**Comment by lippserd** [comment]
Does https://github.com/Icinga/icingaweb2-module-elasticsearch/blob/master/doc/03-Configuration.md help?

**Comment by abunet** [comment]
HI lippserd,
as I said I've already configured the module and tested through the CheckCommand (icingacli elasticsearch check)
Where should I find the  **host action Elasticsearch Events**?

**Comment by lippserd** [comment]
This is fixed w/ #31
