### ISSUE TITLE
[dev.icinga.com #11377] Docs / examples

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-elasticsearch#4]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11377

**Created by mfrosch on 2016-03-14 13:52:59 +00:00**

Assignee: _mfrosch_
Status: _Assigned_ 
Target Version: _1.0.0_
Last Update: _2016-04-05 15:32:49 +00:00 (in Redmine)_

---

-   update README with more examples
-   screenshots
-   logstash example data
-   Dockerfile/compose for testing with Logstash

**Comment by michaeleino** [comment]
really this is very very helpful plugin, but I can't use it!
I just added the elasticsearch host:port & set the index pattern, I can't search yet!

What shall I do, I don't configure elastic with user/password yet & I can connect to it using other 2rd parties.

Please advice with a real implementation procedure, I have already Icinga, ELK up & running & docker is not an option to me yet.

**Comment by lazyfrosch** [comment]
@michaeleino could you please explain your problems in a new issue? There should be some kind of error message?
