### ISSUE TITLE
Provide checks for Icinga based on event contents

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-elasticsearch#41]
Hi,

I'd like to have Icinga checks for certain events.

I think the easiest way for the user would be to make them [IcingaCLI](https://icinga.com/docs/icinga2/latest/doc/10-icinga-template-library/#icingacli) checks.

While I can think of a lot of different ways this might be useful, a simple one might be sufficient. For example:

* Use the filters from one of the "Event Type" configurations
* Add simple conditions like "[icinga][severity]": "Critical"
* Add thresholds like "warning: 1", "critical:5"
* Add timewindows like "15 minutes"
* "A check has a name" like "criticalicinga"

The check could then work like `icingacli elasticsearch criticalicinga -h [hostname]`. If there are more than 5 events matching the filters of the Eventtype and have the field `[icinga][severity]` set to "Critical" on that host it returns Critical.

Cheers,

**Comment by dnsmichi** [comment]
Isn't that already covered with https://github.com/Icinga/icingaweb2-module-elasticsearch/blob/master/application/clicommands/CheckCommand.php ?

**Comment by widhalmt** [comment]
Seems, we are lacking some documentation, then. ;-) I'm on it.
