### ISSUE TITLE
[dev.icinga.com #11379] User restriction based on host setting?

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-elasticsearch#6]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11379

**Created by mfrosch on 2016-03-14 14:01:42 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-04-05 15:33:14 +00:00 (in Redmine)_

---

With mapping to multiple hostname fields.

**Comment by lazyfrosch** [comment]
Idea is that a user should be able to see events of the hosts he is allowed to see.

Currently a use can have 2 permissions:
* See host events
* Is allowed to see specific log types

There is no:
* limitiation on what host's events he can see (integration with permissions of monitoring module)
* limitation that he can only see events of hosts he is allowed to see
