### ISSUE TITLE
[dev.icinga.com #11519] Docker test/dev environment

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-elasticsearch#8]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11519

**Created by mfrosch on 2016-04-05 07:39:14 +00:00**

Assignee: _mfrosch_
Status: _New_ 
Target Version: _1.0.0_
Last Update: _2016-04-05 15:32:50 +00:00 (in Redmine)_

---

Include a Docker test environment with an simple ELK installation.

Add notes to README how to use.

**Changesets**

_2016-04-05 07:58:44 +00:00_ by _(unknown)_ b07f02923b04f8c781dce19ef2fba1891a220868

    Add Docker development environment
    
    refs #11519

_2016-06-30 15:12:05 +00:00_ by _(unknown)_ 51c65b519c3cc3e402da6de65a83ba31ee4a496f

    Update docker test environment
    
    refs #11519

**Comment by lazyfrosch** [comment]
Environment has been updated an documented

See #18
